/*
 * JSP generated by Resin-4.0.35 (built Tue, 12 Feb 2013 10:05:50 PST)
 */

package _jsp._pages._testFlex;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _upload_0document__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    String contextPath = (String) request.getContextPath(); 
    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((contextPath ));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((contextPath ));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((contextPath ));
    out.write(_jsp_string4, 0, _jsp_string4.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8128084403448394333L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("pages/testFlex/upload_document.jsp"), 5708674954058268284L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string3;
  static {
    _jsp_string2 = "/resources/js/jquery.min.js\"></script>\r\n<body>\r\n  <form id=\"fileForm\">\r\n    <input type=\"file\" name=\"documentFile\"/>\r\n    <span id=\"nameSpan\"></span>\r\n  </form>\r\n  <input type=\"button\"  value=\"\u63d0\u4ea4\u6587\u6863\"  id=\"uploadBt\"/>\r\n  <input type=\"button\"  value=\"\u67e5\u770b\u6587\u6863\"  id=\"viewBt\"/>\r\n</body>\r\n \r\n<script type=\"text/javascript\">\r\n    var docName = \"\";\r\n	$(\"#uploadBt\").click(function(){\r\n		var formData = new FormData($(\"#fileForm\")[0]);\r\n		$.ajax({\r\n	         url: \"".toCharArray();
    _jsp_string0 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n".toCharArray();
    _jsp_string1 = "\r\n<title>UPLOAD-TEST</title>\r\n</head>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string4 = "/upload/getDocument.do?documentName=\"+docName); \r\n	});\r\n</script>\r\n</html>".toCharArray();
    _jsp_string3 = "/upload/uploadDocument.do\" ,  \r\n	         type: 'POST',  \r\n	         data: formData,\r\n	         async: false,\r\n	         cache: false,  \r\n	         contentType: false,  \r\n	         processData: false,  \r\n	         success: function (result) {\r\n	        	 if (result.hasErrors) {\r\n	        		 alert(result.errorMessage);\r\n	        	 }else {\r\n	        		 docName = result.data;\r\n	        		$(\"#nameSpan\").html(result.data);\r\n	        	 }\r\n	         }\r\n	    });\r\n	});\r\n	\r\n	$(\"#viewBt\").click(function(){\r\n		window.open(\"".toCharArray();
  }
}
